# Generated by Django 3.1 on 2020-09-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USER', '0002_auto_20200907_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Bonus_Pasiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='USER.data_user')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Bonus_Aktiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_sponsor', models.FloatField(default=0)),
                ('bonus_pairing', models.FloatField(default=0)),
                ('bonus_total', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='USER.data_user')),
            ],
        ),
    ]
