# Generated by Django 3.1 on 2020-09-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USER', '0006_auto_20200909_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='USER.data_user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='USER.data_user')),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='USER.data_user')),
            ],
        ),
        migrations.CreateModel(
            name='Capping_Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capping', models.FloatField(null=True)),
                ('invest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.invest')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus_Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.FloatField(null=True)),
                ('invest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.invest')),
            ],
        ),
    ]
