# Generated by Django 3.1 on 2020-09-10 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd7b4abe-44fb-45d0-b809-a71c253a3cfd'), primary_key=True, serialize=False),
        ),
    ]
