# Generated by Django 3.1 on 2020-09-10 11:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0002_auto_20200910_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_invest',
            name='invest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.invest'),
        ),
        migrations.AlterField(
            model_name='capping_invest',
            name='invest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.invest'),
        ),
        migrations.AlterField(
            model_name='invest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
