# Generated by Django 3.1 on 2020-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_auto_20200907_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='data_user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
